[package]
name = "hello-world-actix-web-tokio"
version = "0.1.0"
authors = ["smallfish <smallfish.xy@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }
