[package]
name = "hello-world-may"
version = "0.1.0"
edition = "2021"

[dependencies]
may_minihttp = { version = "0.1", default-features = false }

[profile.release]
opt-level = 3
codegen-units = 1
panic = 'abort'
lto = true
debug = false
incremental = false
overflow-checks = false
